import { useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, FileText, Copy, CheckCircle2 } from "lucide-react";
import QRCode from "qrcode";
import jsPDF from "jspdf";
import { WiFiConfig } from "./WiFiForm";
import { toast } from "@/hooks/use-toast";
import { useState } from "react";

interface QRDisplayProps {
  config: WiFiConfig;
}

export const QRDisplay = ({ config }: QRDisplayProps) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [copied, setCopied] = useState(false);
  
  const wifiString = `WIFI:T:${config.encryption};S:${config.ssid};P:${config.password};H:${config.hidden};;`;

  useEffect(() => {
    if (canvasRef.current) {
      const canvas = canvasRef.current;
      const ctx = canvas.getContext("2d");
      
      if (config.backgroundImage && ctx) {
        // Load background image
        const img = new Image();
        img.onload = () => {
          canvas.width = 300;
          canvas.height = 300;
          ctx.drawImage(img, 0, 0, 300, 300);
          
          // Generate QR on top
          QRCode.toCanvas(
            canvas,
            wifiString,
            {
              width: 300,
              margin: 2,
              color: {
                dark: "#000000",
                light: "rgba(255,255,255,0.9)",
              },
              errorCorrectionLevel: "H",
            },
            (error) => {
              if (error) {
                toast({
                  title: "QR Generation Error",
                  description: "Failed to generate QR code. Try shortening your password.",
                  variant: "destructive",
                });
                console.error(error);
              }
            }
          );
        };
        img.src = config.backgroundImage;
      } else {
        QRCode.toCanvas(
          canvas,
          wifiString,
          {
            width: 300,
            margin: 2,
            color: {
              dark: "#000000",
              light: "#ffffff",
            },
            errorCorrectionLevel: "M",
          },
          (error) => {
            if (error) {
              toast({
                title: "QR Generation Error",
                description: "Failed to generate QR code. Try shortening your password.",
                variant: "destructive",
              });
              console.error(error);
            }
          }
        );
      }
    }
  }, [wifiString, config.backgroundImage]);

  const handleDownloadPNG = () => {
    if (!canvasRef.current) return;

    canvasRef.current.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `EZ-WI-FI_${config.ssid.replace(/[^a-zA-Z0-9]/g, "_")}.png`;
        link.click();
        URL.revokeObjectURL(url);
        
        toast({
          title: "QR Code Downloaded",
          description: "Your QR code has been saved as PNG",
        });
      }
    });
  };

  const handlePrintPDF = () => {
    if (!canvasRef.current) return;

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // Add title
    pdf.setFontSize(24);
    pdf.text("Guest Wi-Fi", 105, 30, { align: "center" });

    // Add network name
    pdf.setFontSize(16);
    pdf.text(`Network: ${config.ssid}`, 105, 45, { align: "center" });

    // Add credentials if enabled
    if (config.showCredentialsOnPdf) {
      pdf.setFontSize(14);
      pdf.setFont(undefined, "bold");
      pdf.text(`Password: ${config.password || "Open Network"}`, 105, 55, { align: "center" });
      pdf.setFont(undefined, "normal");
    }

    // Add QR code
    const imgData = canvasRef.current.toDataURL("image/png");
    const imgSize = 100; // 100mm square
    const x = (210 - imgSize) / 2; // Center on A4 width (210mm)
    const yPos = config.showCredentialsOnPdf ? 65 : 60;
    pdf.addImage(imgData, "PNG", x, yPos, imgSize, imgSize);

    // Add instructions
    pdf.setFontSize(12);
    const instructY = config.showCredentialsOnPdf ? 180 : 175;
    pdf.text("Scan with your phone's camera to connect", 105, instructY, { align: "center" });
    
    // Add footer
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text("Generated by EZ-WI-FI", 105, 285, { align: "center" });

    pdf.save(`EZ-WI-FI_${config.ssid.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`);
    
    toast({
      title: "PDF Generated",
      description: "Your printable QR code has been downloaded",
    });
  };

  const handleCopyString = async () => {
    try {
      await navigator.clipboard.writeText(wifiString);
      setCopied(true);
      toast({
        title: "Copied to Clipboard",
        description: "Wi-Fi string copied successfully",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Could not copy to clipboard",
        variant: "destructive",
      });
    }
  };

  return (
    <Card className="mx-auto w-full max-w-2xl shadow-medium">
      <CardHeader>
        <CardTitle>Your Wi-Fi QR Code</CardTitle>
        <CardDescription>Scan with any camera app to connect instantly</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex flex-col items-center justify-center space-y-4">
          <div className="rounded-lg bg-white p-6 shadow-soft">
            <canvas ref={canvasRef} className="mx-auto" />
          </div>
          
          <div className="text-center">
            <p className="text-lg font-semibold text-foreground">{config.ssid}</p>
            <p className="text-sm text-muted-foreground">
              {config.encryption === "nopass" ? "Open Network" : "Secured Network"}
            </p>
          </div>
        </div>

        <div className="grid gap-3 sm:grid-cols-3">
          <Button onClick={handleDownloadPNG} size="touch" className="w-full">
            <Download className="mr-2 h-4 w-4" />
            Download PNG
          </Button>
          
          <Button onClick={handlePrintPDF} size="touch" variant="secondary" className="w-full">
            <FileText className="mr-2 h-4 w-4" />
            Print PDF
          </Button>
          
          <Button onClick={handleCopyString} size="touch" variant="outline" className="w-full">
            {copied ? (
              <CheckCircle2 className="mr-2 h-4 w-4" />
            ) : (
              <Copy className="mr-2 h-4 w-4" />
            )}
            {copied ? "Copied!" : "Copy String"}
          </Button>
        </div>

        <div className="rounded-lg border border-border bg-muted/50 p-4">
          <p className="text-xs text-muted-foreground">
            <strong>Tip:</strong> Save or print this QR code and place it where guests can easily scan it. 
            Works with any smartphone camera – no special apps needed!
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
