// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yolcjslhswziywcyummx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbGNqc2xoc3d6aXl3Y3l1bW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODUzNzIsImV4cCI6MjA3Nzc2MTM3Mn0.wFz39HjtHnaZhgX6cZypWMEHjXM6UAVHesm50o4LG98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});